{{- if and .Values.api.enabled .Values.pdb .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "moonin-ingestion-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moonin-ingestion-api.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "moonin-ingestion-api.selectorLabels" . | nindent 6 }}
{{- end }}
