apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "moonin-admin-ui.fullname" . }}
  labels:
    {{- include "moonin-admin-ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "moonin-admin-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "moonin-admin-ui.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "moonin-admin-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: moonin-admin-ui-secret
                optional: true
          env:
            - name: API_BASE_URL
              value: {{ .Values.env.api_base_url | quote }}
            - name: APP_URL
              value: {{ .Values.env.app_url | quote }}
            - name: MOONIN_AGENT_DISCOVERY_API_URL
              value: {{ .Values.env.agent_discovery_api_url | quote }}
            - name: MOONIN_AGENT_INGESTION_API_URL
              value: {{ .Values.env.agent_ingestion_api_url | quote }}
            - name: DEMO_EMAIL
              value: {{ .Values.env.demo_email | quote }}
            - name: AUTO_VERIFY_EMAIL_ON_SIGNUP
              value: {{ .Values.env.auto_verify_email_on_signup | quote }}
            - name: MOONIN_LICENSE
              valueFrom:
                secretKeyRef:
                  name: {{ required "moonin-admin-ui.license.existingSecret is required" .Values.license.existingSecret | quote }}
                  key: {{ required "moonin-admin-ui.license.key is required" .Values.license.key | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
