apiVersion: v1
kind: Service
metadata:
  name: {{ include "moonin-scaling-rules-api.fullname" . }}
  labels:
    {{- include "moonin-scaling-rules-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
      - port: {{ .Values.service.servicePort }}
        targetPort: {{ .Values.service.servicePort }}
        protocol: TCP
        name: service
      - port: {{ .Values.service.backendPort }}
        targetPort: {{ .Values.service.backendPort }}
        protocol: TCP
        name: backend
  selector:
    {{- include "moonin-scaling-rules-api.selectorLabels" . | nindent 4 }}
